<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="LightChatlistUpdater\" />
    <Folder Include="LightChatlistRequestSender\" />
    <Folder Include="LightMessageUpdater\" />
  </ItemGroup>

</Project>
